### ISSUE TITLE
DeepTyper conversion

### ISSUE THREAD

**Issue by travischambers** [tjchambers32/ecs289-final#1]
Need to make compatible with the format that DeepTyper expects in lexer.py.

@VHellendoorn - do you have any advice for tokenizing .py files? I've got around 2000 .py files that include type suggestions. I've also got these same files with all the type suggestions stripped out.

**Comment by travischambers** [comment]
For example, here's one of my .py files:
```
from typing import List

def zsplit(bs: bytes) -> List[bytes]:
    if bs:
        return bs.rstrip(b'\0').split(b'\0')
    else:
        return []
```

And here's my version with type hints stripped out:
```
from typing import List

def zsplit(bs       )               :
    if bs:
        return bs.rstrip(b'\0').split(b'\0')
    else:
        return []
```

**Comment by travischambers** [comment]
I had hoped that I could just drop in these .py files and easily use them with DeepTyper, but it seems that CleanRepos.js and GetTypes.js do more preprocessing than I'd realized.

**Comment by VHellendoorn** [comment]
Hi, yeah the format they expect is a bit more complicated. Basically, it's a tab separated source-target setup, where source is space separated code tokens and target is the corresponding types (and tokens without a type just get set to some generic "O" token). I also build a vocabulary file for each side and run the whole through the txt2ctf translation to make it compatible with CNTK. A perfectly good alternative would be to just find an off the shelf sequence tagger in a more modern framework -- just make sure to handle the untapped tokens well (i.e. mask out their gradients)

**Comment by travischambers** [comment]
I see. I'm looking into using the `flair` framework and training my own model.

I had planned on presenting next Thursday, June 6th - but i was traveling when Prof Devanbu posted the thread to sign up for dates. 

Doing my best for this Thursday's presentation, but I definitely won't have it working very well by then. 

I'll just see how far I get I suppose. It also looks like flair suggests around 1 billion words for training. I've got just over 1 million lines of code, so probably something like 5 or 10 million words.
